---
title: "랜덤 포레스트"
author: 'kuma987'
date: "`r format(Sys.time(), '%Y년 %B %d일')`"
output:
  html_document: 
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_float: yes
  word_document:
    highlight: tango
    reference_docx: korean-template.docx
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 사용 데이터
```{r, results='hide'}
library(mlbench)
library(caret)
library(dplyr)
```

```{r}
#bin은 범주형 변수를 0과 1로 표시한 경우
data("PimaIndiansDiabetes2")
pima <- PimaIndiansDiabetes2
pima <- pima[complete.cases(pima),]
pima_scale <- cbind(as.data.frame(apply(select_if(pima,is.numeric), 2, scale)), diabetes = pima$diabetes)
pima_bin <- pima
pima_bin$diabetes <- as.factor(ifelse(pima_bin$diabetes=='pos',1,0))
pima_scale_bin <- cbind(as.data.frame(apply(select_if(pima,is.numeric), 2, scale)), diabetes = pima_bin$diabetes)
head(pima_scale_bin)
folds <- createFolds(pima$diabetes, k=10)
idx_tr <- unname(unlist(folds[1:5]))
idx_vd <- unname(unlist(folds[6:8]))
idx_ts <- unname(unlist(folds[9:10]))
train <- pima[idx_tr,]
valid <- pima[idx_vd,]
test <- pima[idx_ts,]
train_bin <- pima_bin[idx_tr,]
valid_bin <- pima_bin[idx_vd,]
test_bin <- pima_bin[idx_ts,]
train_scale <- pima_scale[idx_tr,]
valid_scale <- pima_scale[idx_vd,]
test_scale <- pima_scale[idx_ts,]
train_scale_bin <- pima_scale_bin[idx_tr,]
valid_scale_bin <- pima_scale_bin[idx_vd,]
test_scale_bin <- pima_scale_bin[idx_ts,]
```

# 모델링

## caret 패키지
```{r}
model <- train(
  form = diabetes~.,
  data = train,
  trControl = trainControl(method='none'),
  method = 'rf',
  preProcess = c('center','scale')
)
pred_prob <- predict(model, test, type='prob')[,2] #이진분류라서 인덱스를 통해 두 번째 클래스에 속할 확률로 지정
pred_class <- predict(model, test, type='raw')
```


## randomForest 패키지
```{r, results='hide'}
library(randomForest)
```

```{r}
model <- randomForest(diabetes~., train, ntree = 100, proximity = T, importance = T)
importance(model) #정확도, 불순도 개선 정도 모두 높은 변수가 중요 변수
varImpPlot(model) #위 결과를 시각화 (오름차순 정렬로 인해 더 보기 쉬움)
pred_prob <- predict(model, test, type='prob')[,2] #이진분류라서 인덱스를 통해 두 번째 클래스에 속할 확률로 지정
pred_class <- predict(model, test, type='response') 
```


# 모델 평가
```{r, results='hide'}
library(ROCR)
```

## 이진분류의 경우
```{r}
caret::confusionMatrix(pred_class, test$diabetes, positive='pos')
precision <- posPredValue(pred_class, test$diabetes, positive='pos')
recall <- sensitivity(pred_class, test$diabetes, positive='pos')
F1_score <- (2*precision*recall)/(precision+recall)
roc_curve <- prediction(pred_prob, test$diabetes)
plot(performance(roc_curve,'tpr','fpr'))
abline(a=0, b=1,lty=2, col='black')
performance(roc_curve,'auc')@y.values # auc 값
```

## 다지분류의 경우
```{r}
caret::confusionMatrix(pred_class, test$diabetes)
```


