---
title: "영어 텍스트 분석"
author: 'kuma987'
date: "`r format(Sys.time(), '%Y년 %B %d일')`"
output:
  html_document: 
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_float: yes
  word_document:
    highlight: tango
    reference_docx: korean-template.docx
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

해당 문서는 간단하게 수행하는 방법만 작성 (자격증 시험 기출 문제 전용) 
실제 분석을 위해서는 더 공부한 후 옵션을 적용하는 법을 알아야 한다  



# 패키지 준비
```{r, results='hide'}
library(tm)
library(SnowballC)
library(NLP)
library(wordcloud2)
library(plyr)
library(stringr)
library(ggplot2)
library(dplyr)
```

# 텍스트 불러오기
```{r}
raw_txt <- readLines("/Users/JGH/Desktop/github/R-Notebook/data/Obama.txt")
head(raw_txt)
```

# TDM 생성
```{r}
raw_corp <- VCorpus(VectorSource(raw_txt))
clean_corpus <- function(corpus){
  corpus <- tm_map(corpus, content_transformer(tolower)) # 소문자 처리
  corpus <- tm_map(corpus, removeWords, stopwords()) # 불용어 제거
  corpus <- tm_map(corpus, removePunctuation) # 구두점 제거
  corpus <- tm_map(corpus, removeNumbers) # 숫자 제거
  corpus <- tm_map(corpus, stripWhitespace) # 공백 제거
  corpus <- tm_map(corpus, content_transformer(PlainTextDocument)) # 충돌 방지
  return(corpus)
}

pro_corp <- clean_corpus(raw_corp)
# control 아래 다양한 옵션을 추가할 수 있음
# 옵션에 따라 단어-빈도 행렬 뿐 아니라, TF-IDF도 추출 가능
tdm <- TermDocumentMatrix(pro_corp)
```

# 단어-빈도 차트 생성
```{r}
df <- as.data.frame(as.matrix(tdm))
v <- sort(rowSums(df), decreasing=T)
wordcount <- data.frame(word=names(v), freq=v)
head(wordcount)
```
# 시각화

```{r, results='hide'}
# 나눔고딕 폰트 (맥에서 한글 깨짐 방지)
library(showtext)
font_add_google("Nanum Gothic","nanumgothic")
showtext_auto()
```


```{r}
# 빈도수 막대 시각화
ggplot(wordcount[1:10,]) + geom_bar(stat='identity',
                                    aes(x=reorder(word,-freq), y=freq, fill=word)) +
       ggtitle('상위 10개 단어 빈도') + labs(x='단어', y='빈도') +
       theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# 빈도수 파이 차트
ggplot(wordcount[1:10,], aes(x='', y=freq, fill=word)) +
  geom_bar(stat='identity') +
  theme_void() +
  coord_polar('y', start=10) +
  geom_text(aes(label = word),
            position = position_stack(vjust=0.5),
            color = 'black', size=3, check_overlap = T) +
  labs(title = '상위 10개 단어 파이 차트') +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# 워드 클라우드
# 아마 RMD에서 wordcloud2 두 번 시각화가 되지 않아서 화면 안 나올 듯
wordcloud2(wordcount, fontFamily='나눔바른고딕', size=0.8)
```

# 번외 : 단어끼리 같은 문장에 등장한 횟수
```{r}
m <- as.matrix(tdm)
adjmat <- m %*% t(m)
adjmat[1:6,1:6]
diag(adjmat) = 0
```


