---
title: "데이터 살펴보기"
author: 'kuma987'
date: "`r format(Sys.time(), '%Y년 %B %d일')`"
output:
  html_document: 
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_float: yes
  word_document:
    highlight: tango
    reference_docx: korean-template.docx
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 사용 데이터
```{r}
library(mlbench)
data("PimaIndiansDiabetes2")
pima <- PimaIndiansDiabetes2
NROW(pima)
```

# 결측치 보기
## 전체 결측치 수
```{r}
sum(is.na(pima))
```
## 칼럼별 결측치 수
```{r}
colSums(is.na(pima))
```

# 결측치 처리
## 1. 결측치 제거
### 전체 결측치 제거
```{r}
pima_complete_NA <- pima[complete.cases(pima),]
sum(is.na(pima_complete_NA))
colSums(is.na(pima_complete_NA))
NROW(pima_complete_NA)
```
### 특정 칼럼 결측치 제거
```{r}
pima_complete_NA_columns <- pima[!is.na(pima$triceps),]
pima_complete_NA_columns <- pima_complete_NA_columns[!is.na(pima_complete_NA_columns$insulin),]
sum(is.na(pima_complete_NA_columns))
colSums(is.na(pima_complete_NA_columns))
NROW(pima_complete_NA_columns)
```

## 2. 결측치 대체
### 연속형 칼럼
```{r}
#중앙값으로 대체한 경우 (필요에 따라 중앙값(median), 최빈값(범주형 칼럼 참고) 등으로 대체하기도 함)
pima_impute <- pima
pima_impute$triceps <- ifelse(is.na(pima_impute$triceps),
                       mean(pima_impute$triceps, na.rm=T), 
                       pima_impute$triceps)
colSums(is.na(pima_impute))
```

### 범주형 칼럼
```{r, results='hide'}
#범주형 변수에 임의로 NA 생성
library(caret)
```

```{r}
pima_dia_impute <- pima
idx_rd <- createDataPartition(pima_dia_impute$diabetes, p = 0.7, times=1,list=F)
pima_dia_impute$diabetes[-idx_rd] <- NA
table(pima_dia_impute$diabetes, useNA='always')

#최빈값 구하는 함수
getmode <- function(x){
  uniqx <- unique(x)
  uniqx[which.max(tabulate(match(x,uniqx)))]
}

#최빈값으로 대체한 경우
pima_dia_impute$diabetes <- ifelse(is.na(pima_dia_impute$diabetes),
                            getmode(pima_dia_impute$diabetes),
                            pima_dia_impute$diabetes)
table(pima_dia_impute$diabetes, useNA='always')
```

