---
title: "이상치"
author: 'kuma987'
date: "`r format(Sys.time(), '%Y년 %B %d일')`"
output:
  html_document: 
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_float: yes
  word_document:
    highlight: tango
    reference_docx: korean-template.docx
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 사용 데이터
```{r}
library(mlbench)
data("PimaIndiansDiabetes2")
pima <- PimaIndiansDiabetes2
#결측치 제거
pima <- pima[complete.cases(pima),]
```

```{r, results='hide'}
library(dplyr)
```

```{r}
#수치형 자료만 추출
pima_num <- select_if(pima, is.numeric)
```



# 각종 이상치 기준
```{r}
#ESD : 평균으로부터 3 표준편차 만큼 떨어진 값
esd_max <- mean(pima_num$pregnant) + 3*sd(pima_num$pregnant)
esd_min <- mean(pima_num$pregnant) - 3*sd(pima_num$pregnant)
#기하평균 활용 : 기하평균으로부터 2.5 표준편차 만큼 떨어진 값
geo_max <- exp(mean(log(pima_num$pregnant))) + 2.5*sd(pima_num$pregnant)
geo_min <- exp(mean(log(pima_num$pregnant))) - 2.5*sd(pima_num$pregnant)
#IQR 활용 : 중앙값으로부터 1.5 IQR 만큼 떨어진 값
IQR_max <- median(pima_num$pregnant) + 1.5*IQR(pima_num$pregnant)
IQR_min <- median(pima_num$pregnant) - 1.5*IQR(pima_num$pregnant)
```


# 이상치 대체 (이상치 기준 : IQR, 이상치를 기준점으로 대체) 
## 1. 특정 칼럼 이상치 대체
```{r}
boxplot(pima_num$pregnant)
IQR_max <- median(pima_num$pregnant) + 1.5*IQR(pima_num$pregnant)
IQR_min <- median(pima_num$pregnant) - 1.5*IQR(pima_num$pregnant)
pima_preg_out <- pima_num
pima_preg_out$pregnant <- ifelse(pima_preg_out$pregnant >= IQR_max,
                            IQR_max,
                            pima_preg_out$pregnant)
pima_preg_out$pregnant <- ifelse(pima_preg_out$pregnant <= IQR_min,
                            IQR_min,
                            pima_preg_out$pregnant)
boxplot(pima_preg_out$pregnant)
```

## 2. 전체 칼럼 이상치 대체
```{r}
boxplot(pima_num)
pima_out <- pima_num
for (i in 1:NROW(names(pima_out))) {
  IQR_max <- median(pima_out[,i]) + 1.5*IQR(pima_out[,i])
  IQR_min <- median(pima_out[,i]) - 1.5*IQR(pima_out[,i])
  pima_out[,i] <- ifelse(pima_out[,i] >= IQR_max,
                         IQR_max,
                         pima_out[,i])
  pima_out[,i] <- ifelse(pima_out[,i] <= IQR_min,
                         IQR_min,
                         pima_out[,i])
}
boxplot(pima_out)
```

# 이상치 제거
이상치 대체와 같은 방식으로 수행하되, 대체값을 NA로 지정한 후, complete.cases 함수 활용해서 제거
