---
title: "시각화"
author: 'kuma987'
date: "`r format(Sys.time(), '%Y년 %B %d일')`"
output:
  html_document: 
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_float: yes
  word_document:
    highlight: tango
    reference_docx: korean-template.docx
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 사용 데이터
```{r}
library(mlbench)
data("PimaIndiansDiabetes2")
pima <- PimaIndiansDiabetes2
#결측치 제거
pima <- pima[complete.cases(pima),]
```

```{r, results='hide'}
library(dplyr)
library(tidyr)
library(ggplot2)
pima_num <- select_if(pima, is.numeric)
pima_class <- select_if(pima, is.factor)
```

# 연속형 변수
```{r}
ggplot(pivot_longer(pima_num,everything())) + geom_histogram(aes(x=value))+
  facet_wrap(~name, scales='free_x')
```


# 범주형 변수
```{r}
ggplot(pivot_longer(pima_class,everything())) + geom_bar(aes(x=value))+
  facet_wrap(~name, scales='free_x')
```

# 상관계수
```{r, results='hide'}
library(corrgram)
```

```{r}
cor_mtrx <- cor(pima_num, method='pearson')
corrgram(cor_mtrx, upper.panel = panel.conf)
```


