---
title: "정규화"
author: 'kuma987'
date: "`r format(Sys.time(), '%Y년 %B %d일')`"
output:
  html_document: 
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_float: yes
  word_document:
    highlight: tango
    reference_docx: korean-template.docx
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 사용 데이터
```{r}
a <- c(-17,-3,-2,-5,-23,0,1,4,6,16,21)
b <- -a
c <- data.frame(a,b)
c
```


# 표준화
표본정규분포로 변환
기본함수인 'scale' 이용
```{r}
std <- apply(c,2,scale)
std
```


# 최대최소 정규화
데이터를 0~1 사이의 값으로 변환
이상치에 취약
```{r}
minmax <- function(x){
  result <- (x-min(x))/(max(x)-min(x))
  return(result)
}
mm <- apply(c,2,minmax)
mm
```

# Robust 정규화
데이터를 중앙값이 0, IQR이 1이 되도록 변환
이상치의 영향 최소화
```{r}
robust <- function(x){
  result <- (x-median(x))/IQR(x)
  return(result)
}
ro <- apply(c,2,robust)
ro
```

# MaxAbs 정규화
데이터의 절대값이 가장 큰 수를 1 또는 -1로 변환하여 데이터의 범위를 줄이는 방식
```{r}
maxabs <- function(x){
  result <- x/(max(abs(max(x)),abs(min(x))))
  return(result)
}
mab <- apply(c,2,maxabs)
mab
```



