---
title: "데이터 분할"
author: 'kuma987'
date: "`r format(Sys.time(), '%Y년 %B %d일')`"
output:
  html_document: 
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_float: yes
  word_document:
    highlight: tango
    reference_docx: korean-template.docx
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 사용 데이터
```{r}
library(mlbench)
data("PimaIndiansDiabetes2")
pima <- PimaIndiansDiabetes2
#결측치 제거
pima <- pima[complete.cases(pima),]
```

```{r, resuls = 'hide'}
library(dplyr)
library(caret)
library(ggplot2)
```
caret 패키지 이용
자동으로 층화추출 적용
해당 문서에서는 범주형 변수를 기준으로 데이터를 분할하였지만, 범주형 변수가 아닌 연속형 변수도 적용 가능

# createDataPartition
이분할만 가능
```{r}
# train:test = 7:3
table(pima$diabetes)
idx_tr <- createDataPartition(pima$diabetes, p = 0.7, times=1, list=F)
train <- pima[idx_tr,]
test <- pima[-idx_tr,]
table(train$diabetes)
table(test$diabetes)
pima_grp <- mutate(pima, idx=seq(1:NROW(pima)), grp=ifelse(idx %in% idx_tr,'tr','ts'))
pima_grp$grp <- as.factor(pima_grp$grp)
ggplot(pima_grp) + geom_bar(aes(x=grp, fill=diabetes), position='fill') + labs(y='prop')
```

# createFolds
원하는 집단만큼 분할 가능
그런데 가끔씩 분할이 이상하게 이루어질 수 있으니 반드시 table 확인할 것
```{r}
# train:valid:test = 5:3:2
table(pima$diabetes)
folds <- createFolds(pima$diabetes, k=10)
idx_tr <- unname(unlist(folds[1:5]))
idx_vd <- unname(unlist(folds[6:8]))
idx_ts <- unname(unlist(folds[9:10]))
train <- pima[idx_tr,]
valid <- pima[idx_vd,]
test <- pima[idx_ts,]
table(train$diabetes)
table(valid$diabetes)
table(test$diabetes)
pima_grp2 <- mutate(pima, idx=seq(1:NROW(pima)), grp = ifelse(idx %in% idx_tr, 'tr',
                                                             ifelse(idx %in% idx_vd, 'vd','ts')))
pima_grp2$grp <- as.factor(pima_grp2$grp)
ggplot(pima_grp2) + geom_bar(aes(x=grp, fill=diabetes), position='fill') + labs(y='prop')

```




