---
title: "데이터 불균형"
author: 'kuma987'
date: "`r format(Sys.time(), '%Y년 %B %d일')`"
output:
  html_document: 
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_float: yes
  word_document:
    highlight: tango
    reference_docx: korean-template.docx
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 사용 데이터
```{r}
library(mlbench)
data("PimaIndiansDiabetes2")
pima <- PimaIndiansDiabetes2
#결측치 제거
pima <- pima[complete.cases(pima),]
```

```{r, results='hide'}
library(caret)
library(ggplot2)
```

```{r}
table(pima$diabetes)
ggplot(pima) + geom_bar(aes(x=diabetes, fill=diabetes),position='identity')
```

# 다운샘플링
다수 클래스 중 일부만 사용하는 방식
데이터 손실 발생

## 랜덤 다운샘플링
다수 클래스 중 일부를 추출하는 과정에서, 아예 랜덤
```{r}
down <- downSample(subset(pima,select=-diabetes), pima$diabetes, yname='diabetes')
table(down$diabetes)
ggplot(down) + geom_bar(aes(x=diabetes, fill=diabetes),position='identity')
```

# 업샘플링
소수 클래수를 복사 또는 추가로 생성하는 방식
과적합 가능성 존재
검증 성능이 떨어질 가능성 존재

## 랜덤 업샘플링
소수 클래스 중 일부를 복사
```{r}
up <- upSample(subset(pima,select=-diabetes), pima$diabetes, yname='diabetes')
table(up$diabetes)
ggplot(up) + geom_bar(aes(x=diabetes, fill=diabetes),position='identity')
```

## SMOTE
소수 클래스에서 중심이 되는 데이터와 주변 데이터 사이에 가상의 직선을 만든 후, 그 위에 데이터를 추가하는 방법
R에 존재하는 함수의 경우 파라미터에 따라 데이터 수가 달라지는 것을 보면, 조금 더 공부할 필요가 있음
```{r, eval=FALSE}
library(DMwR)
smote <- SMOTE(diabetes~, pima, perc.over=100, perc.under=200)
# ((소수 클래스 데이터 수) * (perc.over))/100 만큼 소수 클래스 데이터 추가
# ((위 식에 의한 추가 데이터) * (perc.under))/100 = 다수 클래스 데이터의 최종 개수
```
최근 R 버전에서 DMwR을 제공하지 않아서 수행되지 않음;;

